from typing import Optional

class Game:
    def __init__(self, seed: Optional[int] = None): ...
    def reset(self, seed: Optional[int] = None): ...
    def step(self, dir_x: int, dir_y: int): ...
    def render(self): ...

class GameState:
    Continue: int
    Finished: int
